# Generated by Django 2.1 on 2021-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
