# Generated by Django 2.1 on 2021-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210222_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=50)),
                ('areacode', models.IntegerField(max_length=10)),
                ('aredistrict', models.CharField(default='HYD', max_length=20)),
            ],
        ),
    ]
