# Generated by Django 2.1 on 2021-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='areacode',
            field=models.IntegerField(),
        ),
    ]
