# Generated by Django 2.1 on 2021-02-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20210223_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='aredistrict',
            new_name='areadistrict',
        ),
    ]
