# Generated by Django 2.1 on 2021-03-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20210223_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='areamember',
            field=models.CharField(default='satya', max_length=100),
        ),
    ]
